---
title: "STAT 345 Midterm Project"
font: 12pt
due: "Due April 4"
output: 
  #pdf_document: default
  #word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(devtools)
devtools::install_github("abresler/nbastatR@aba9179ef644f263387c1536d6ddd26104d79cf4")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)

library(nbastatR)
jazz_10 <- teams_shots(teams = "Utah Jazz", seasons = 2010)
jazz_15 <- teams_shots(teams = "Utah Jazz", seasons = 2015)
jazz_20 <- teams_shots(teams = "Utah Jazz", seasons = 2020)
jazz_25 <- teams_shots(teams = "Utah Jazz", seasons = 2025)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)

plot_shot_chart <- function(dat, year) {
  make_percentage <- round((sum(dat$isShotMade) / count(dat)) * 100)
  
  bins <- dat %>%
    mutate(xbin = round(locationX / 10) * 10,
           ybin = round(locationY / 10) * 10) %>%
    group_by(xbin, ybin) %>%
    summarize(total = n(),
              made = sum(isShotMade),
              .groups = "drop") %>%
    mutate(ratio = made / total,
           more_makes = made > (total / 2))
  
  ggplot() +
    geom_tile(data = bins,
              aes(x = xbin, y = ybin, fill = total),
              width = 10, height = 10) +
    scale_fill_gradient(name = "Shot Frequency", 
                        trans = "log", 
                        low = "skyblue", high = "purple",
                        breaks = c(min(bins$total), max(bins$total)),
                        labels = c("least", "most"),
                        guide = guide_colorbar(direction = "horizontal",
                                               title.position = "top",
                                               barwidth = 8, barheight = 1)) +
    
    geom_point(data = bins %>% filter(more_makes),
              aes(x = xbin, y = ybin, color = "More shots made than missed"),
              size = 0.2, show.legend = TRUE) +
    scale_color_manual(name = "", 
                       values = c("More shots made than missed" = "yellow"),
                       labels = c("More shots made\nthan missed"),
                       guide = guide_legend(override.aes = list(size = 5))) +
    
    # Hoop
    annotate("path", x = 7.5 * cos(seq(0, 2 * pi, length.out = 100)), 
             y = 7.5 * sin(seq(0, 2 * pi, length.out = 100)), color = "black") +
    # Backboard
    annotate("segment", x = -30, xend = 30, y = -7.5, yend = -7.5, color = "black") +
    # Outer box (paint)
    annotate("rect", xmin = -80, xmax = 80, ymin = -47.5, ymax = 142.5, color = "black", fill = NA) +
    # Inner box (paint)
    annotate("rect", xmin = -60, xmax = 60, ymin = -47.5, ymax = 142.5, color = "black", fill = NA) +
    # Free throw arcs
    annotate("path", x = 60 * cos(seq(0, pi, length.out = 100)), y = 142.5 + 60 * sin(seq(0, pi, length.out = 100)), color = "black") +
    annotate("path", x = 60 * cos(seq(pi, 2 * pi, length.out = 100)), y = 142.5 + 60 * sin(seq(pi, 2 * pi, length.out = 100)), color = "black", linetype = "dashed") +
    # Restricted arc
    annotate("path", x = 40 * cos(seq(0, pi, length.out = 100)), y = 40 * sin(seq(0, pi, length.out = 100)), color = "black") +
    # Three-point line
    annotate("segment", x = -220, xend = -220, y = -47.5, yend = 92.5, color = "black") +
    annotate("segment", x = 220, xend = 220, y = -47.5, yend = 92.5, color = "black") +
    annotate("path", x = 237.5 * cos(seq(22 * pi / 180, 158 * pi / 180, length.out = 100)), y = 237.5 * sin(seq(22 * pi / 180, 158 * pi / 180, length.out = 100)), color = "black") +
    # Center circle
    annotate("path", x = 60 * cos(seq(0, pi, length.out = 100)), y = 422.5 + 60 * sin(seq(pi, 2*pi, length.out = 100)), color = "black") +
    annotate("path", x = 20 * cos(seq(0, pi, length.out = 100)), y = 422.5 + 20 * sin(seq(pi, 2*pi, length.out = 100)), color = "black") +
    # Add the court boundary lines
    annotate("rect", xmin = -250, xmax = 250, ymin = -47.5, ymax = 422.5, color = "black", fill = NA) +
    # Set court limits to accurately reflect dimensions
    coord_fixed(ratio = 1) +
    xlim(-250, 250) +
    ylim(-50, 460) +
    # Adjust labels
    labs(title = as.character(year)) +
    theme_void() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
    annotate("text", x = 0, y = 457, label = paste0(as.character(make_percentage), "% made"), size = 3) 
}
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
plt10 <- plot_shot_chart(jazz_10, 2010)
plt15 <- plot_shot_chart(jazz_15, 2015)
plt20 <- plot_shot_chart(jazz_20, 2020)
plt25 <- plot_shot_chart(jazz_25, 2025)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(cowplot)
library(patchwork)

legend <- get_legend(plt10)
final <- (plt10 + plt15 + plt20 + plt25) + 
  plot_layout(guides = "collect") + 
  plot_annotation(title = "Utah Jazz shots over 15 years", 
                  theme = theme(plot.title = element_text(size = 17, face = "bold", hjust = 0.5)))
print(final)
```

### Observations:
* Our shots used to be spread more evenly across the court
* Shots are becoming increasingly concentrated in the three second area and around the three point line
* The percentage of made shots has slightly decreased
* Shots near the hoop are made more than missed
